import type { Category } from '@/types'

export type BadgeType = 'Recomendado' | 'Oferta' | 'Nuevo' | 'Mejor valor' | 'Gaming' | 'Premium'

export interface CatalogProduct {
  id: string
  slug: string
  name: string
  shortName: string
  brand: string
  category: Category
  description: string
  price: number
  originalPrice?: number
  currency: string
  rating: number
  reviewCount: number
  image: string
  badge?: BadgeType
  featured?: boolean
  trending?: boolean
  year: number
  affiliateUrl: string
  store: 'amazon' | 'pccomponentes' | 'mediamarkt'
  reviewSlug?: string
}

const products: CatalogProduct[] = [
  /* ── PORTÁTILES ─────────────────────────────────────────── */
  {
    id: 'macbook-air-m3',
    slug: 'macbook-air-m3',
    name: 'Apple MacBook Air 13" M3 (2024)',
    shortName: 'MacBook Air M3',
    brand: 'Apple',
    category: 'portatiles',
    description: 'El ultrabook más equilibrado del mercado. Chip M3, 18h de autonomía, sin ventiladores y solo 1,24 kg.',
    price: 1299,
    currency: '€',
    rating: 4.7,
    reviewCount: 2847,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
    badge: 'Recomendado',
    featured: true,
    trending: true,
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/dp/B0CWDPTXMD',
    store: 'amazon',
    reviewSlug: 'macbook-air-m3',
  },
  {
    id: 'asus-rog-zephyrus-g14',
    slug: 'asus-rog-zephyrus-g14-2024',
    name: 'ASUS ROG Zephyrus G14 (2024)',
    shortName: 'ROG Zephyrus G14',
    brand: 'ASUS ROG',
    category: 'portatiles',
    description: 'RTX 4070 + OLED 2,8K 120Hz en 1,6 kg. El portátil gaming más elegante del mercado.',
    price: 1899,
    originalPrice: 2099,
    currency: '€',
    rating: 4.6,
    reviewCount: 1234,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80',
    badge: 'Gaming',
    featured: true,
    trending: true,
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/asus-rog-zephyrus-g14',
    store: 'amazon',
    reviewSlug: 'asus-rog-zephyrus-g14',
  },
  {
    id: 'dell-xps-15-9530',
    slug: 'dell-xps-15-9530',
    name: 'Dell XPS 15 9530 (2023)',
    shortName: 'Dell XPS 15',
    brand: 'Dell',
    category: 'portatiles',
    description: 'Pantalla OLED 3.5K, Intel Core i7-13700H y RTX 4060 en un chasis de aluminio premium.',
    price: 1799,
    currency: '€',
    rating: 4.4,
    reviewCount: 987,
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
    badge: 'Premium',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/dell-xps-15',
    store: 'amazon',
  },
  {
    id: 'lenovo-thinkpad-x1-carbon',
    slug: 'lenovo-thinkpad-x1-carbon-gen11',
    name: 'Lenovo ThinkPad X1 Carbon Gen 11',
    shortName: 'ThinkPad X1 Carbon',
    brand: 'Lenovo',
    category: 'portatiles',
    description: 'El referente en portátiles de empresa. Teclado icónico, 1,12 kg y 15h de autonomía.',
    price: 1649,
    currency: '€',
    rating: 4.5,
    reviewCount: 1543,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/lenovo-thinkpad-x1-carbon',
    store: 'amazon',
  },
  {
    id: 'hp-spectre-x360-14',
    slug: 'hp-spectre-x360-14',
    name: 'HP Spectre x360 14 (2024)',
    shortName: 'HP Spectre x360',
    brand: 'HP',
    category: 'portatiles',
    description: '2-en-1 premium con pantalla OLED táctil, Intel Core Ultra 7 y diseño joya en apenas 1,4 kg.',
    price: 1549,
    originalPrice: 1699,
    currency: '€',
    rating: 4.3,
    reviewCount: 765,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80',
    badge: 'Oferta',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/hp-spectre-x360',
    store: 'amazon',
  },
  {
    id: 'microsoft-surface-laptop-5',
    slug: 'microsoft-surface-laptop-5',
    name: 'Microsoft Surface Laptop 5 13.5"',
    shortName: 'Surface Laptop 5',
    brand: 'Microsoft',
    category: 'portatiles',
    description: 'PixelSense táctil de 13,5 pulgadas, Intel Core i5-1245U y 17h de autonomía en un diseño minimalista.',
    price: 1099,
    currency: '€',
    rating: 4.2,
    reviewCount: 543,
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80',
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/microsoft-surface-laptop-5',
    store: 'amazon',
  },
  {
    id: 'razer-blade-16-2024',
    slug: 'razer-blade-16-2024',
    name: 'Razer Blade 16 (2024)',
    shortName: 'Razer Blade 16',
    brand: 'Razer',
    category: 'portatiles',
    description: 'RTX 4090 Laptop en un chasis de aluminio CNC de 2,14 kg. El gaming laptop definitivo sin compromiso.',
    price: 3999,
    currency: '€',
    rating: 4.5,
    reviewCount: 432,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80',
    badge: 'Gaming',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/razer-blade-16',
    store: 'amazon',
  },
  {
    id: 'acer-swift-5-2024',
    slug: 'acer-swift-5-2024',
    name: 'Acer Swift 5 (2024)',
    shortName: 'Acer Swift 5',
    brand: 'Acer',
    category: 'portatiles',
    description: 'Ultra-ligero de 0,99 kg con pantalla táctil OLED 2K, Intel Core Ultra 5 y 12h de batería.',
    price: 1299,
    originalPrice: 1499,
    currency: '€',
    rating: 4.2,
    reviewCount: 321,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80',
    badge: 'Oferta',
    year: 2024,
    affiliateUrl: 'https://www.pccomponentes.com/acer-swift-5',
    store: 'pccomponentes',
  },
  {
    id: 'lg-gram-16-2024',
    slug: 'lg-gram-16-2024',
    name: 'LG Gram 16 (2024)',
    shortName: 'LG Gram 16',
    brand: 'LG',
    category: 'portatiles',
    description: 'El portátil de 16 pulgadas más ligero: 1,19 kg, certificación MIL-STD-810 y 22h de autonomía.',
    price: 1199,
    currency: '€',
    rating: 4.3,
    reviewCount: 654,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
    badge: 'Mejor valor',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/lg-gram-16',
    store: 'amazon',
  },
  {
    id: 'asus-zenbook-14-oled',
    slug: 'asus-zenbook-14-oled',
    name: 'ASUS ZenBook 14 OLED (2024)',
    shortName: 'ZenBook 14 OLED',
    brand: 'ASUS',
    category: 'portatiles',
    description: 'Pantalla OLED 2.8K a 120Hz con chip AMD Ryzen 7 8845HS. Potencia y elegancia en 1,2 kg.',
    price: 1099,
    currency: '€',
    rating: 4.4,
    reviewCount: 876,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80',
    badge: 'Nuevo',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/asus-zenbook-14-oled',
    store: 'amazon',
  },
  {
    id: 'lenovo-ideapad-slim-5-pro',
    slug: 'lenovo-ideapad-slim-5-pro',
    name: 'Lenovo IdeaPad Slim 5 Pro 16"',
    shortName: 'IdeaPad Slim 5 Pro',
    brand: 'Lenovo',
    category: 'portatiles',
    description: 'Pantalla IPS 2.5K 120Hz, Ryzen 7 7745HX y 32GB RAM a un precio muy competitivo para creativos.',
    price: 899,
    originalPrice: 1099,
    currency: '€',
    rating: 4.1,
    reviewCount: 432,
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
    badge: 'Oferta',
    year: 2023,
    affiliateUrl: 'https://www.pccomponentes.com/lenovo-ideapad-slim-5-pro',
    store: 'pccomponentes',
  },
  {
    id: 'macbook-pro-14-m3',
    slug: 'macbook-pro-14-m3',
    name: 'Apple MacBook Pro 14" M3 Pro',
    shortName: 'MacBook Pro 14" M3',
    brand: 'Apple',
    category: 'portatiles',
    description: 'Pantalla Liquid Retina XDR ProMotion 120Hz, chip M3 Pro con 12 núcleos y hasta 22h de autonomía.',
    price: 2199,
    currency: '€',
    rating: 4.9,
    reviewCount: 3241,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
    badge: 'Premium',
    featured: true,
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/macbook-pro-14-m3-pro',
    store: 'amazon',
  },

  /* ── MÓVILES ─────────────────────────────────────────────── */
  {
    id: 'iphone-15-pro',
    slug: 'iphone-15-pro',
    name: 'Apple iPhone 15 Pro',
    shortName: 'iPhone 15 Pro',
    brand: 'Apple',
    category: 'moviles',
    description: 'Chip A17 Pro, titanio, botón Acción y USB-C con velocidades USB 3.0. La cámara móvil definitiva.',
    price: 1229,
    currency: '€',
    rating: 4.5,
    reviewCount: 5432,
    image: 'https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800&q=80',
    badge: 'Recomendado',
    featured: true,
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/iphone-15-pro',
    store: 'amazon',
    reviewSlug: 'iphone-15-pro',
  },
  {
    id: 'samsung-galaxy-s24-ultra',
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    shortName: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'moviles',
    description: 'S Pen integrado, zoom 10x óptico, 200MP y Snapdragon 8 Gen 3. El Android más completo.',
    price: 1359,
    originalPrice: 1499,
    currency: '€',
    rating: 4.7,
    reviewCount: 4123,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
    badge: 'Recomendado',
    featured: true,
    trending: true,
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/samsung-galaxy-s24-ultra',
    store: 'amazon',
    reviewSlug: 'samsung-galaxy-s24-ultra',
  },
  {
    id: 'google-pixel-8-pro',
    slug: 'google-pixel-8-pro',
    name: 'Google Pixel 8 Pro',
    shortName: 'Pixel 8 Pro',
    brand: 'Google',
    category: 'moviles',
    description: 'La mejor cámara computacional. Chip Tensor G3, 7 años de updates garantizados y pantalla LTPO 120Hz.',
    price: 999,
    originalPrice: 1099,
    currency: '€',
    rating: 4.5,
    reviewCount: 2876,
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80',
    badge: 'Oferta',
    trending: true,
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/google-pixel-8-pro',
    store: 'amazon',
  },
  {
    id: 'oneplus-12',
    slug: 'oneplus-12',
    name: 'OnePlus 12 5G',
    shortName: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'moviles',
    description: 'Snapdragon 8 Gen 3, carga de 100W SuperVOOC, cámara Hasselblad y AMOLED 2K 120Hz.',
    price: 899,
    currency: '€',
    rating: 4.4,
    reviewCount: 1654,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
    badge: 'Mejor valor',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/oneplus-12',
    store: 'amazon',
  },
  {
    id: 'samsung-galaxy-s24-plus',
    slug: 'samsung-galaxy-s24-plus',
    name: 'Samsung Galaxy S24+',
    shortName: 'Galaxy S24+',
    brand: 'Samsung',
    category: 'moviles',
    description: 'Pantalla de 6,7 pulgadas QHD+ 120Hz, Snapdragon 8 Gen 3 y 4.900mAh con carga de 45W.',
    price: 1099,
    originalPrice: 1199,
    currency: '€',
    rating: 4.4,
    reviewCount: 2341,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
    badge: 'Oferta',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/samsung-galaxy-s24-plus',
    store: 'amazon',
  },
  {
    id: 'sony-xperia-1-vi',
    slug: 'sony-xperia-1-vi',
    name: 'Sony Xperia 1 VI',
    shortName: 'Xperia 1 VI',
    brand: 'Sony',
    category: 'moviles',
    description: 'Zoom óptico de primer nivel (1-7.1x continuo), sensor grande de 1/1.35" y audio profesional.',
    price: 1299,
    currency: '€',
    rating: 4.3,
    reviewCount: 876,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
    badge: 'Premium',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/sony-xperia-1-vi',
    store: 'amazon',
  },
  {
    id: 'samsung-galaxy-z-fold-6',
    slug: 'samsung-galaxy-z-fold-6',
    name: 'Samsung Galaxy Z Fold 6',
    shortName: 'Galaxy Z Fold 6',
    brand: 'Samsung',
    category: 'moviles',
    description: 'Plegable flagship con pantalla interior de 7,6 pulgadas, S Pen compatible y Snapdragon 8 Gen 3.',
    price: 1899,
    currency: '€',
    rating: 4.3,
    reviewCount: 1234,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
    badge: 'Nuevo',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/samsung-galaxy-z-fold-6',
    store: 'amazon',
  },
  {
    id: 'nothing-phone-2a',
    slug: 'nothing-phone-2a',
    name: 'Nothing Phone (2a)',
    shortName: 'Nothing Phone 2a',
    brand: 'Nothing',
    category: 'moviles',
    description: 'Diseño transparente único con Glyph Interface, Dimensity 7200 Pro y batería de 5.000mAh.',
    price: 349,
    currency: '€',
    rating: 4.0,
    reviewCount: 987,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
    badge: 'Mejor valor',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/nothing-phone-2a',
    store: 'amazon',
  },
  {
    id: 'motorola-edge-50-ultra',
    slug: 'motorola-edge-50-ultra',
    name: 'Motorola Edge 50 Ultra',
    shortName: 'Edge 50 Ultra',
    brand: 'Motorola',
    category: 'moviles',
    description: 'Pantalla pOLED curva 144Hz, cámara de 50MP con OIS óptico avanzado y carga de 125W.',
    price: 699,
    originalPrice: 799,
    currency: '€',
    rating: 4.2,
    reviewCount: 543,
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80',
    badge: 'Oferta',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/motorola-edge-50-ultra',
    store: 'amazon',
  },
  {
    id: 'xiaomi-14-pro',
    slug: 'xiaomi-14-pro',
    name: 'Xiaomi 14 Pro',
    shortName: 'Xiaomi 14 Pro',
    brand: 'Xiaomi',
    category: 'moviles',
    description: 'Lente Leica de 1 pulgada, Snapdragon 8 Gen 3 y carga de 120W HyperCharge. Flagship asombroso.',
    price: 1099,
    currency: '€',
    rating: 4.5,
    reviewCount: 1876,
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80',
    badge: 'Recomendado',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/xiaomi-14-pro',
    store: 'amazon',
  },
  {
    id: 'realme-gt-6',
    slug: 'realme-gt-6',
    name: 'Realme GT 6',
    shortName: 'Realme GT 6',
    brand: 'Realme',
    category: 'moviles',
    description: 'Snapdragon 8s Gen 3, pantalla AMOLED 120Hz y carga SuperVOOC 120W al mejor precio del segmento.',
    price: 599,
    originalPrice: 699,
    currency: '€',
    rating: 4.1,
    reviewCount: 432,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
    badge: 'Mejor valor',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/realme-gt-6',
    store: 'amazon',
  },

  /* ── AURICULARES ─────────────────────────────────────────── */
  {
    id: 'sony-wh-1000xm5',
    slug: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    shortName: 'Sony XM5',
    brand: 'Sony',
    category: 'auriculares',
    description: 'La mejor cancelación de ruido del mercado over-ear. 30h de autonomía, LDAC y multipoint.',
    price: 299,
    currency: '€',
    rating: 4.6,
    reviewCount: 8432,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    badge: 'Recomendado',
    featured: true,
    trending: true,
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/sony-wh-1000xm5',
    store: 'amazon',
    reviewSlug: 'sony-wh-1000xm5',
  },
  {
    id: 'airpods-pro-2',
    slug: 'airpods-pro-2',
    name: 'Apple AirPods Pro 2ª gen.',
    shortName: 'AirPods Pro 2',
    brand: 'Apple',
    category: 'auriculares',
    description: 'Los mejores TWS si tienes iPhone. ANC adaptativa, audio espacial personalizado y 30h totales.',
    price: 279,
    currency: '€',
    rating: 4.4,
    reviewCount: 12341,
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&q=80',
    badge: 'Recomendado',
    featured: true,
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/airpods-pro-2',
    store: 'amazon',
    reviewSlug: 'airpods-pro-2',
  },
  {
    id: 'bose-qc-ultra',
    slug: 'bose-quietcomfort-ultra',
    name: 'Bose QuietComfort Ultra Headphones',
    shortName: 'Bose QC Ultra',
    brand: 'Bose',
    category: 'auriculares',
    description: 'El rival directo del XM5. ANC de élite, Bose Immersive Audio y 24h de autonomía.',
    price: 449,
    currency: '€',
    rating: 4.5,
    reviewCount: 3456,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    badge: 'Premium',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/bose-qc-ultra',
    store: 'amazon',
  },
  {
    id: 'sennheiser-momentum-4',
    slug: 'sennheiser-momentum-4',
    name: 'Sennheiser Momentum 4 Wireless',
    shortName: 'Momentum 4',
    brand: 'Sennheiser',
    category: 'auriculares',
    description: 'Calidad de sonido Sennheiser con 60h de autonomía, ANC eficaz y diseño elegante.',
    price: 299,
    originalPrice: 349,
    currency: '€',
    rating: 4.4,
    reviewCount: 2134,
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80',
    badge: 'Oferta',
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/sennheiser-momentum-4',
    store: 'amazon',
  },
  {
    id: 'sony-wf-1000xm5',
    slug: 'sony-wf-1000xm5-tws',
    name: 'Sony WF-1000XM5',
    shortName: 'Sony WF-1000XM5',
    brand: 'Sony',
    category: 'auriculares',
    description: 'Los mejores TWS del mercado con LDAC. ANC líder en in-ear, 36h totales y diseño compacto.',
    price: 279,
    originalPrice: 329,
    currency: '€',
    rating: 4.5,
    reviewCount: 4321,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
    badge: 'Oferta',
    trending: true,
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/sony-wf-1000xm5',
    store: 'amazon',
  },
  {
    id: 'samsung-galaxy-buds-3-pro',
    slug: 'samsung-galaxy-buds-3-pro',
    name: 'Samsung Galaxy Buds 3 Pro',
    shortName: 'Galaxy Buds 3 Pro',
    brand: 'Samsung',
    category: 'auriculares',
    description: 'El mejor TWS del ecosistema Samsung. ANC adaptativa, audio 360° y hasta 30h con el estuche.',
    price: 229,
    currency: '€',
    rating: 4.3,
    reviewCount: 1876,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
    badge: 'Nuevo',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/samsung-galaxy-buds-3-pro',
    store: 'amazon',
  },
  {
    id: 'anker-soundcore-liberty-4-pro',
    slug: 'anker-soundcore-liberty-4-pro',
    name: 'Anker Soundcore Liberty 4 Pro',
    shortName: 'Liberty 4 Pro',
    brand: 'Anker',
    category: 'auriculares',
    description: 'La alternativa económica con ANC eficaz, 28h de autonomía y LDAC a un precio accesible.',
    price: 99,
    currency: '€',
    rating: 4.0,
    reviewCount: 2341,
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80',
    badge: 'Mejor valor',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/anker-soundcore-liberty-4-pro',
    store: 'amazon',
  },
  {
    id: 'jbl-tour-pro-3',
    slug: 'jbl-tour-pro-3',
    name: 'JBL Tour Pro 3',
    shortName: 'JBL Tour Pro 3',
    brand: 'JBL',
    category: 'auriculares',
    description: 'Pantalla táctil en el estuche de carga, ANC adaptativa y 40h de autonomía total.',
    price: 249,
    currency: '€',
    rating: 4.2,
    reviewCount: 987,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
    badge: 'Nuevo',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/jbl-tour-pro-3',
    store: 'amazon',
  },
  {
    id: 'jabra-evolve2-85',
    slug: 'jabra-evolve2-85',
    name: 'Jabra Evolve2 85',
    shortName: 'Jabra Evolve2 85',
    brand: 'Jabra',
    category: 'auriculares',
    description: 'El estándar de la industria en auriculares de empresa. 37h de batería, ANC eficaz y certificación UC.',
    price: 449,
    originalPrice: 499,
    currency: '€',
    rating: 4.4,
    reviewCount: 1543,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    badge: 'Premium',
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/jabra-evolve2-85',
    store: 'amazon',
  },

  /* ── TABLETS ─────────────────────────────────────────────── */
  {
    id: 'ipad-air-m2',
    slug: 'ipad-air-m2',
    name: 'Apple iPad Air M2 11" (2024)',
    shortName: 'iPad Air M2',
    brand: 'Apple',
    category: 'tablets',
    description: 'El iPad que la mayoría debería comprar. Chip M2, compatible con Apple Pencil Pro y 10h de batería.',
    price: 799,
    currency: '€',
    rating: 4.4,
    reviewCount: 3456,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    badge: 'Recomendado',
    featured: true,
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/ipad-air-m2',
    store: 'amazon',
    reviewSlug: 'ipad-air-m2',
  },
  {
    id: 'ipad-pro-m4-13',
    slug: 'ipad-pro-m4-13',
    name: 'Apple iPad Pro M4 13" (2024)',
    shortName: 'iPad Pro M4 13"',
    brand: 'Apple',
    category: 'tablets',
    description: 'La tablet más potente del mundo. Pantalla OLED Ultra Retina XDR, chip M4 y solo 5,1 mm de grosor.',
    price: 1299,
    currency: '€',
    rating: 4.8,
    reviewCount: 2341,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    badge: 'Premium',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/ipad-pro-m4-13',
    store: 'amazon',
  },
  {
    id: 'samsung-tab-s9-ultra',
    slug: 'samsung-galaxy-tab-s9-ultra',
    name: 'Samsung Galaxy Tab S9 Ultra',
    shortName: 'Tab S9 Ultra',
    brand: 'Samsung',
    category: 'tablets',
    description: 'Pantalla AMOLED de 14,6 pulgadas, Snapdragon 8 Gen 2 y S Pen incluido. La mejor Android tablet.',
    price: 1099,
    originalPrice: 1249,
    currency: '€',
    rating: 4.6,
    reviewCount: 1876,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    badge: 'Oferta',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/samsung-tab-s9-ultra',
    store: 'amazon',
  },
  {
    id: 'microsoft-surface-pro-10',
    slug: 'microsoft-surface-pro-10',
    name: 'Microsoft Surface Pro 10 for Business',
    shortName: 'Surface Pro 10',
    brand: 'Microsoft',
    category: 'tablets',
    description: '2-en-1 empresarial con Intel Core Ultra, pantalla táctil 120Hz y nueva tecla Copilot.',
    price: 1099,
    currency: '€',
    rating: 4.2,
    reviewCount: 654,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/surface-pro-10',
    store: 'amazon',
  },
  {
    id: 'google-pixel-tablet',
    slug: 'google-pixel-tablet',
    name: 'Google Pixel Tablet (2023)',
    shortName: 'Pixel Tablet',
    brand: 'Google',
    category: 'tablets',
    description: 'Android puro, 11 pulgadas, altavoces de alta fidelidad y base de carga que la convierte en pantalla inteligente.',
    price: 679,
    originalPrice: 749,
    currency: '€',
    rating: 4.1,
    reviewCount: 1234,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    badge: 'Oferta',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/google-pixel-tablet',
    store: 'amazon',
  },
  {
    id: 'xiaomi-pad-6s-pro',
    slug: 'xiaomi-pad-6s-pro',
    name: 'Xiaomi Pad 6S Pro 12.4"',
    shortName: 'Xiaomi Pad 6S Pro',
    brand: 'Xiaomi',
    category: 'tablets',
    description: 'Pantalla 3K 144Hz, Snapdragon 8 Gen 2 y carga de 120W en una tablet de 12,4 pulgadas.',
    price: 549,
    currency: '€',
    rating: 4.3,
    reviewCount: 876,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    badge: 'Mejor valor',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/xiaomi-pad-6s-pro',
    store: 'amazon',
  },
  {
    id: 'samsung-tab-s9-fe',
    slug: 'samsung-galaxy-tab-s9-fe',
    name: 'Samsung Galaxy Tab S9 FE',
    shortName: 'Tab S9 FE',
    brand: 'Samsung',
    category: 'tablets',
    description: 'La entrada más accesible al ecosistema Tab S9 con S Pen incluido y pantalla TFT de 10,9 pulgadas.',
    price: 449,
    originalPrice: 549,
    currency: '€',
    rating: 4.0,
    reviewCount: 1654,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    badge: 'Oferta',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/samsung-tab-s9-fe',
    store: 'amazon',
  },

  /* ── MONITORES ───────────────────────────────────────────── */
  {
    id: 'lg-27gr95qe-oled',
    slug: 'lg-27gr95qe-oled',
    name: 'LG 27GR95QE-B OLED Gaming',
    shortName: 'LG 27GR95QE OLED',
    brand: 'LG',
    category: 'monitores',
    description: 'El mejor monitor gaming: OLED QHD 240Hz con 0,03ms y DCI-P3 98,5%. Un antes y un después.',
    price: 699,
    originalPrice: 849,
    currency: '€',
    rating: 4.5,
    reviewCount: 1543,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Gaming',
    featured: true,
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/lg-27gr95qe',
    store: 'amazon',
    reviewSlug: 'lg-27gr95qe-oled',
  },
  {
    id: 'samsung-odyssey-oled-g9',
    slug: 'samsung-odyssey-oled-g9-49',
    name: 'Samsung Odyssey OLED G9 49"',
    shortName: 'Odyssey OLED G9',
    brand: 'Samsung',
    category: 'monitores',
    description: 'Monitor ultrawide 32:9 OLED de 49 pulgadas, 240Hz y resolución Dual-QHD. Inmersión total.',
    price: 1499,
    originalPrice: 1799,
    currency: '€',
    rating: 4.6,
    reviewCount: 876,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Gaming',
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/samsung-odyssey-oled-g9',
    store: 'amazon',
  },
  {
    id: 'dell-ultrasharp-u2723qe',
    slug: 'dell-ultrasharp-u2723qe',
    name: 'Dell UltraSharp U2723QE 27" 4K',
    shortName: 'Dell U2723QE',
    brand: 'Dell',
    category: 'monitores',
    description: 'Monitor de trabajo 4K IPS Black con USB-C 90W, hub integrado y calibración de fábrica Delta-E<2.',
    price: 849,
    currency: '€',
    rating: 4.5,
    reviewCount: 2134,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Recomendado',
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/dell-u2723qe',
    store: 'amazon',
  },
  {
    id: 'alienware-aw3423dwf',
    slug: 'alienware-aw3423dwf-oled',
    name: 'Alienware AW3423DWF QD-OLED 34"',
    shortName: 'Alienware AW3423DWF',
    brand: 'Alienware',
    category: 'monitores',
    description: 'QD-OLED curvo 34" ultrawide a 165Hz con DCI-P3 99,3%, contraste infinito y 0,1ms GTG.',
    price: 999,
    originalPrice: 1199,
    currency: '€',
    rating: 4.7,
    reviewCount: 3456,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Recomendado',
    trending: true,
    year: 2023,
    affiliateUrl: 'https://www.amazon.es/alienware-aw3423dwf',
    store: 'amazon',
  },
  {
    id: 'lg-32un880-b-ergo',
    slug: 'lg-32un880-b-ergo',
    name: 'LG 32UN880-B Ergo 4K 32"',
    shortName: 'LG 32UN880 Ergo',
    brand: 'LG',
    category: 'monitores',
    description: 'Monitor 4K IPS con soporte ergonómico de brazo integrado, USB-C 60W y HDR600.',
    price: 549,
    originalPrice: 699,
    currency: '€',
    rating: 4.3,
    reviewCount: 1234,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Oferta',
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/lg-32un880',
    store: 'amazon',
  },
  {
    id: 'benq-pd3225u',
    slug: 'benq-pd3225u',
    name: 'BenQ PD3225U 4K 32" Designer',
    shortName: 'BenQ PD3225U',
    brand: 'BenQ',
    category: 'monitores',
    description: 'El mejor monitor para diseñadores: 4K IPS, cobertura DCI-P3 95%, Thunderbolt 4 y hardware calibration.',
    price: 999,
    currency: '€',
    rating: 4.6,
    reviewCount: 765,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Premium',
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/benq-pd3225u',
    store: 'amazon',
  },
  {
    id: 'philips-279c9',
    slug: 'philips-279c9',
    name: 'Philips 279C9 27" 4K USB-C',
    shortName: 'Philips 279C9',
    brand: 'Philips',
    category: 'monitores',
    description: 'Monitor 4K IPS con puerto USB-C 65W, cámara emergente integrada 5MP y diseño sin marco.',
    price: 399,
    currency: '€',
    rating: 4.1,
    reviewCount: 876,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Mejor valor',
    year: 2022,
    affiliateUrl: 'https://www.amazon.es/philips-279c9',
    store: 'amazon',
  },
  {
    id: 'msi-mag-274qrfde-qd',
    slug: 'msi-mag-274qrfde-qd',
    name: 'MSI MAG 274QRFDE-QD 27" QD-IPS',
    shortName: 'MSI MAG 274QRFDE',
    brand: 'MSI',
    category: 'monitores',
    description: 'QD-IPS 2K 180Hz con respuesta de 1ms, FreeSync Premium Pro y 98% DCI-P3. Gaming y productividad.',
    price: 449,
    originalPrice: 549,
    currency: '€',
    rating: 4.4,
    reviewCount: 654,
    image: 'https://images.unsplash.com/photo-1593640408182-31c228ff7edd?w=800&q=80',
    badge: 'Oferta',
    year: 2024,
    affiliateUrl: 'https://www.amazon.es/msi-mag-274qrfde',
    store: 'amazon',
  },
]

export default products

export function getProductsByCategory(category: Category): CatalogProduct[] {
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts(limit = 6): CatalogProduct[] {
  return products.filter((p) => p.featured).slice(0, limit)
}

export function getTrendingProducts(limit = 8): CatalogProduct[] {
  return products.filter((p) => p.trending).slice(0, limit)
}

export function getProductBySlug(slug: string): CatalogProduct | undefined {
  return products.find((p) => p.slug === slug)
}

export function getAllProducts(): CatalogProduct[] {
  return products
}

export function searchProducts(query: string): CatalogProduct[] {
  const q = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
  )
}
